#ifndef TACHYON_MATH_ELLIPTIC_CURVES_SHORT_WEIERSTRASS_SW_CURVE_CONFIG_TRAITS_H_
#define TACHYON_MATH_ELLIPTIC_CURVES_SHORT_WEIERSTRASS_SW_CURVE_CONFIG_TRAITS_H_

namespace tachyon {
namespace math {

template <typename T>
struct SWCurveConfigTraits;

}
}  // namespace tachyon

#endif  // TACHYON_MATH_ELLIPTIC_CURVES_SHORT_WEIERSTRASS_SW_CURVE_CONFIG_TRAITS_H_
