#ifndef TACHYON_CRYPTO_COMMITMENTS_MIXED_MATRIX_COMMITMENT_SCHEME_TRAITS_FORWARD_H_
#define TACHYON_CRYPTO_COMMITMENTS_MIXED_MATRIX_COMMITMENT_SCHEME_TRAITS_FORWARD_H_

namespace tachyon::crypto {

template <typename MMCS>
struct MixedMatrixCommitmentSchemeTraits;

}  // namespace tachyon::crypto

#endif  // TACHYON_CRYPTO_COMMITMENTS_MIXED_MATRIX_COMMITMENT_SCHEME_TRAITS_FORWARD_H_
