#ifndef TACHYON_CRYPTO_COMMITMENTS_VECTOR_COMMITMENT_SCHEME_TRAITS_FORWARD_H_
#define TACHYON_CRYPTO_COMMITMENTS_VECTOR_COMMITMENT_SCHEME_TRAITS_FORWARD_H_

namespace tachyon::crypto {

template <typename VCS>
struct VectorCommitmentSchemeTraits;

}  // namespace tachyon::crypto

#endif  // TACHYON_CRYPTO_COMMITMENTS_VECTOR_COMMITMENT_SCHEME_TRAITS_FORWARD_H_
