events {
    worker_connections 4096; ## Default: 1024
}

http {
    server {
        location /cache/ {
        # The path to the directory where nginx should store the cache contents.
        root /cache;
        # Allow PUT
        dav_methods PUT;
        # Allow nginx to create the /ac and /cas subdirectories.
        create_full_put_path on;
        # The maximum size of a single file.
        client_max_body_size 1G;
        autoindex on;
        allow all;
        }
    }
}
