// This is generated by //tachyon/cc/math/elliptic_curves/generator
#ifndef TACHYON_CC_MATH_ELLIPTIC_CURVES_BN_BN254_FQ2_H_
#define TACHYON_CC_MATH_ELLIPTIC_CURVES_BN_BN254_FQ2_H_

#include <string.h>

#include <ostream>

#include "tachyon/c/math/elliptic_curves/bn/bn254/fp2.h"
#include "tachyon/cc/export.h"

namespace tachyon::cc::math::bn254 {

class TACHYON_CC_EXPORT Fp2 {
 private:
  tachyon_bn254_fq c0_;
  tachyon_bn254_fq c1_;

 public:
  Fp2() = default;
  explicit Fp2(tachyon_bn254_fp2 fp2) {}
  Fp2(tachyon_bn254_fq c0, tachyon_bn254_fq c1) {
    memcpy(c0_.limbs, c0.limbs, sizeof(uint64_t) * 4);
    memcpy(c1_.limbs, c1.limbs, sizeof(uint64_t) * 4);
  }

  const tachyon_bn254_fq& c0() const { return c0_; }
  tachyon_bn254_fq& c0() { return c0_; }
  const tachyon_bn254_fq* c0_ptr() const { return &c0_; }

  const tachyon_bn254_fq& c1() const { return c1_; }
  tachyon_bn254_fq& c1() { return c1_; }
  const tachyon_bn254_fq* c1_ptr() const { return &c1_; }

  static Fp2 Zero() {
    return Fp2(tachyon_bn254_fq_zero(), tachyon_bn254_fq_zero());
  }

  static Fp2 One() {
    return Fp2(tachyon_bn254_fq_one(), tachyon_bn254_fq_zero());
  }

  static Fp2 Random() {
    return Fp2(tachyon_bn254_fq_random(), tachyon_bn254_fq_random());
  }

  Fp2 operator+(const Fp2& other) const {
    return Fp2(tachyon_bn254_fq_add(&c0_, &other.c0_),
               tachyon_bn254_fq_add(&c1_, &other.c1_));
  }

  Fp2& operator+=(const Fp2& other) {
    c0_ = tachyon_bn254_fq_add(&c0_, &other.c0_);
    c1_ = tachyon_bn254_fq_add(&c1_, &other.c1_);
    return *this;
  }

  Fp2 operator-(const Fp2& other) const {
    return Fp2(tachyon_bn254_fq_sub(&c0_, &other.c0_),
               tachyon_bn254_fq_sub(&c1_, &other.c1_));
  }

  Fp2& operator-=(const Fp2& other) {
    c0_ = tachyon_bn254_fq_sub(&c0_, &other.c0_);
    c1_ = tachyon_bn254_fq_sub(&c1_, &other.c1_);
    return *this;
  }

  //   Fp2 operator*(const Fp2& other) const {
  //     return Fr(tachyon_bn254_fr_mul(&value_, &other.value_));
  //   }

  //   Fr& operator*=(const Fr& other) {
  //     value_ = tachyon_bn254_fr_mul(&value_, &other.value_);
  //     return *this;
  //   }

  //   Fr operator/(const Fr& other) const {
  //     return Fr(tachyon_bn254_fr_div(&value_, &other.value_));
  //   }

  //   Fr& operator/=(const Fr& other) {
  //     value_ = tachyon_bn254_fr_div(&value_, &other.value_);
  //     return *this;
  //   }

  //   Fr operator-() const { return Fr(tachyon_bn254_fr_neg(&value_)); }

  //   Fr Double() const { return Fr(tachyon_bn254_fr_dbl(&value_)); }

  //   Fr Square() const { return Fr(tachyon_bn254_fr_sqr(&value_)); }

  //   Fr Inverse() const { return Fr(tachyon_bn254_fr_inv(&value_)); }

  //   bool operator==(const Fr& other) const {
  //     return tachyon_bn254_fr_eq(&value_, &other.value_);
  //   }

  //   bool operator!=(const Fr& other) const {
  //     return tachyon_bn254_fr_ne(&value_, &other.value_);
  //   }

  //   bool operator>(const Fr& other) const {
  //     return tachyon_bn254_fr_gt(&value_, &other.value_);
  //   }

  //   bool operator>=(const Fr& other) const {
  //     return tachyon_bn254_fr_ge(&value_, &other.value_);
  //   }

  //   bool operator<(const Fr& other) const {
  //     return tachyon_bn254_fr_lt(&value_, &other.value_);
  //   }

  //   bool operator<=(const Fr& other) const {
  //     return tachyon_bn254_fr_le(&value_, &other.value_);
  //   }

  //   std::string ToString() const;

  //  private:
  //   tachyon_bn254_fr value_;
};

// TACHYON_CC_EXPORT std::ostream& operator<<(std::ostream& os, const Fr&
// value);

}  // namespace tachyon::cc::math::bn254

#endif  // TACHYON_CC_MATH_ELLIPTIC_CURVES_BN_BN254_FQ_H_
