#ifndef TACHYON_C_ZK_PLONK_HALO2_CONSTANTS_H_
#define TACHYON_C_ZK_PLONK_HALO2_CONSTANTS_H_

#define TACHYON_HALO2_GWC_PCS 0
#define TACHYON_HALO2_SHPLONK_PCS 1

#define TACHYON_HALO2_HALO2_LS 0
#define TACHYON_HALO2_LOG_DERIVATIVE_HALO2_LS 1

#define TACHYON_HALO2_BLAKE2B_TRANSCRIPT 0
#define TACHYON_HALO2_POSEIDON_TRANSCRIPT 1
#define TACHYON_HALO2_SHA256_TRANSCRIPT 2

#endif  // TACHYON_C_ZK_PLONK_HALO2_CONSTANTS_H_
