#ifndef TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FQ_FAIL_H_
#define TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FQ_FAIL_H_

extern "C" void Fq_fail();

#endif  // TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FQ_FAIL_H_
