#ifndef TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FR_FAIL_H_
#define TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FR_FAIL_H_

extern "C" void Fr_fail();

#endif  // TACHYON_MATH_ELLIPTIC_CURVES_BN_BN254_FR_FAIL_H_
