[package]
name = "plonky3_batch_fft_benchmark"
version = "0.0.1"
authors = ["The Tachyon Authors <tachyon-discuss@kroma.network>"]
edition = "2021"
description = """
Plonky3 FFT Batch Benchmark
"""
license = "MIT OR Apache-2.0"
repository = "https://github.com/kroma-network/tachyon"
readme = "README.md"
categories = ["cryptography"]
keywords = ["tachyon", "benchmark", "plonky3"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
p3-baby-bear = "0.1.4-succinct"
p3-dft = "0.1.4-succinct"
p3-field = "0.1.4-succinct"
p3-matrix = "0.1.4-succinct"
tachyon_rs = { path = "../../../tachyon/rs" }

[dependencies.p3-maybe-rayon]
version = "0.1.4-succinct"
features = ["rayon"]
