#ifndef TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FEC_FAIL_H_
#define TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FEC_FAIL_H_

extern "C" void Fec_fail();

#endif  // TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FEC_FAIL_H_
