#ifndef TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FNEC_FAIL_H_
#define TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FNEC_FAIL_H_

extern "C" void Fnec_fail();

#endif  // TACHYON_MATH_ELLIPTIC_CURVES_SECP_SECP256K1_FNEC_FAIL_H_
