#include "absl/strings/str_replace.h"

#include "tachyon/base/console/iostream.h"
#include "tachyon/base/files/file_path_flag.h"
#include "tachyon/base/files/file_util.h"
#include "tachyon/base/flag/flag_parser.h"
#include "tachyon/base/strings/string_util.h"
#include "tachyon/build/generator_util.h"

namespace tachyon {

struct GenerationConfig {
  base::FilePath out;
  std::string type;
  int fq_limb_nums;
  int fr_limb_nums;

  int Write(const std::string& content) const;

  int GeneratePrimeFieldHdr(std::string_view suffix) const;
  int GenerateFqHdr() const;
  int GenerateFrHdr() const;
  int GenerateG1Hdr() const;
};

int GenerationConfig::Write(const std::string& content) const {
  if (!base::WriteFile(out, content)) return 1;
  return 0;
}

int GenerationConfig::GeneratePrimeFieldHdr(std::string_view suffix) const {
  std::vector<std::string_view> tpl = {
      "// This is generated by //tachyon/c/math/elliptic_curves/generator",
      "#ifndef %{header_guard_macro}",
      "#define %{header_guard_macro}",
      "",
      "#include <stdint.h>",
      "",
      "#include \"tachyon/c/export.h\"",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_%{suffix} {",
      "  uint64_t limbs[%{limb_nums}];",
      "};",
      "",
      "#endif  // %{header_guard_macro}",
  };

  std::string tpl_content = absl::StrJoin(tpl, "\n");

  std::string content = absl::StrReplaceAll(
      tpl_content,
      {
          {"%{header_guard_macro}", build::BazelOutToHdrGuardMacro(out)},
          {"%{type}", type},
          {"%{suffix}", std::string(suffix)},
          {"%{limb_nums}",
           absl::StrCat(suffix == "fq" ? fq_limb_nums : fr_limb_nums)},
      });
  return Write(content);
}

int GenerationConfig::GenerateFqHdr() const {
  return GeneratePrimeFieldHdr("fq");
}

int GenerationConfig::GenerateFrHdr() const {
  return GeneratePrimeFieldHdr("fr");
}

int GenerationConfig::GenerateG1Hdr() const {
  // clang-format off
  std::string_view tpl[] = {
      "// This is generated by //tachyon/c/math/elliptic_curves/generator",
      "#ifndef %{header_guard_macro}",
      "#define %{header_guard_macro}",
      "",
      "#include \"tachyon/c/export.h\"",
      "#include \"%{header_path}\"",
      "",
      "struct TACHYON_C_EXPORT __attribute__((aligned(32))) tachyon_%{type}_g1_affine {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  // needs to occupy 32 byte",
      "  // NOTE(chokobole): See LimbsAlignment() in tachyon/math/base/big_int.h",
      "  bool infinity = false;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_projective {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  tachyon_%{type}_fq z;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_jacobian {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  tachyon_%{type}_fq z;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_xyzz {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  tachyon_%{type}_fq zz;",
      "  tachyon_%{type}_fq zzz;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_point2 {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_point3 {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  tachyon_%{type}_fq z;",
      "};",
      "",
      "struct TACHYON_C_EXPORT tachyon_%{type}_g1_point4 {",
      "  tachyon_%{type}_fq x;",
      "  tachyon_%{type}_fq y;",
      "  tachyon_%{type}_fq z;",
      "  tachyon_%{type}_fq w;",
      "};",
      "",
      "#endif  // %{header_guard_macro}",
  };
  // clang-format on
  std::string tpl_content = absl::StrJoin(tpl, "\n");

  std::string header_guard_macro = build::BazelOutToHdrGuardMacro(out);
  base::FilePath hdr_path = build::BazelOutToHdrPath(out);
  std::string basename = hdr_path.BaseName().value();
  std::string header_path = hdr_path.DirName().Append("fq.h").value();
  std::string content = absl::StrReplaceAll(
      tpl_content, {
                       {"%{header_guard_macro}", header_guard_macro},
                       {"%{header_path}", header_path},
                       {"%{type}", type},
                   });
  return Write(content);
}

int RealMain(int argc, char** argv) {
  GenerationConfig config;

  base::FlagParser parser;
  parser.AddFlag<base::FilePathFlag>(&config.out)
      .set_long_name("--out")
      .set_help("path to output");
  parser.AddFlag<base::StringFlag>(&config.type)
      .set_long_name("--type")
      .set_required();
  parser.AddFlag<base::IntFlag>(&config.fq_limb_nums)
      .set_long_name("--fq_limb_nums")
      .set_required();
  parser.AddFlag<base::IntFlag>(&config.fr_limb_nums)
      .set_long_name("--fr_limb_nums")
      .set_required();

  std::string error;
  if (!parser.Parse(argc, argv, &error)) {
    tachyon_cerr << error << std::endl;
    return 1;
  }

  if (base::EndsWith(config.out.value(), "fq.h")) {
    return config.GenerateFqHdr();
  } else if (base::EndsWith(config.out.value(), "fr.h")) {
    return config.GenerateFrHdr();
  } else if (base::EndsWith(config.out.value(), "g1.h")) {
    return config.GenerateG1Hdr();
  } else {
    tachyon_cerr << "not supported suffix:" << config.out << std::endl;
    return 1;
  }
}

}  // namespace tachyon

int main(int argc, char** argv) { return tachyon::RealMain(argc, argv); }
