// This is generated by //tachyon/c/math/elliptic_curves/generator
#ifndef TACHYON_C_MATH_ELLIPTIC_CURVES_BN_BN254_G2_H_
#define TACHYON_C_MATH_ELLIPTIC_CURVES_BN_BN254_G2_H_

#include "tachyon/c/export.h"
#include "tachyon/c/math/elliptic_curves/bn/bn254/fp2.h"

struct __attribute__((aligned(32))) tachyon_bn254_g2_affine {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  // needs to occupy 32 byte
  // NOTE(chokobole): See LimbsAlignment() in tachyon/math/base/big_int.h
  bool infinity;
};

struct tachyon_bn254_g2_projective {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  tachyon_bn254_fp2 z;
};

struct tachyon_bn254_g2_jacobian {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  tachyon_bn254_fp2 z;
};

struct tachyon_bn254_g2_xyzz {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  tachyon_bn254_fp2 zz;
  tachyon_bn254_fp2 zzz;
};

struct tachyon_bn254_g2_point2 {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
};

struct tachyon_bn254_g2_point3 {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  tachyon_bn254_fp2 z;
};

struct tachyon_bn254_g2_point4 {
  tachyon_bn254_fp2 x;
  tachyon_bn254_fp2 y;
  tachyon_bn254_fp2 z;
  tachyon_bn254_fp2 w;
};

#ifdef __cplusplus
extern "C" {
#endif

TACHYON_C_EXPORT void tachyon_bn254_g2_init();

TACHYON_C_EXPORT tachyon_bn254_g2_affine tachyon_bn254_g2_affine_zero();

TACHYON_C_EXPORT tachyon_bn254_g2_projective tachyon_bn254_g2_projective_zero();

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_zero();

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_zero();

TACHYON_C_EXPORT tachyon_bn254_g2_affine tachyon_bn254_g2_affine_generator();

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_generator();

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian
tachyon_bn254_g2_jacobian_generator();

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_generator();

TACHYON_C_EXPORT tachyon_bn254_g2_affine tachyon_bn254_g2_affine_random();

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_random();

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_random();

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_random();

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_affine_add(
    const tachyon_bn254_g2_affine* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_projective tachyon_bn254_g2_projective_add(
    const tachyon_bn254_g2_projective* a, const tachyon_bn254_g2_projective* b);

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_add_mixed(const tachyon_bn254_g2_projective* a,
                                      const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_add(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_jacobian* b);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_add_mixed(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_add(
    const tachyon_bn254_g2_xyzz* a, const tachyon_bn254_g2_xyzz* b);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_add_mixed(
    const tachyon_bn254_g2_xyzz* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_affine_sub(
    const tachyon_bn254_g2_affine* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_projective tachyon_bn254_g2_projective_sub(
    const tachyon_bn254_g2_projective* a, const tachyon_bn254_g2_projective* b);

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_sub_mixed(const tachyon_bn254_g2_projective* a,
                                      const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_sub(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_jacobian* b);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian tachyon_bn254_g2_jacobian_sub_mixed(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_sub(
    const tachyon_bn254_g2_xyzz* a, const tachyon_bn254_g2_xyzz* b);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz tachyon_bn254_g2_xyzz_sub_mixed(
    const tachyon_bn254_g2_xyzz* a, const tachyon_bn254_g2_affine* b);

TACHYON_C_EXPORT tachyon_bn254_g2_affine
tachyon_bn254_g2_affine_neg(const tachyon_bn254_g2_affine* a);

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_neg(const tachyon_bn254_g2_projective* a);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian
tachyon_bn254_g2_jacobian_neg(const tachyon_bn254_g2_jacobian* a);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz
tachyon_bn254_g2_xyzz_neg(const tachyon_bn254_g2_xyzz* a);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian
tachyon_bn254_g2_affine_dbl(const tachyon_bn254_g2_affine* a);

TACHYON_C_EXPORT tachyon_bn254_g2_projective
tachyon_bn254_g2_projective_dbl(const tachyon_bn254_g2_projective* a);

TACHYON_C_EXPORT tachyon_bn254_g2_jacobian
tachyon_bn254_g2_jacobian_dbl(const tachyon_bn254_g2_jacobian* a);

TACHYON_C_EXPORT tachyon_bn254_g2_xyzz
tachyon_bn254_g2_xyzz_dbl(const tachyon_bn254_g2_xyzz* a);

bool TACHYON_C_EXPORT tachyon_bn254_g2_affine_eq(
    const tachyon_bn254_g2_affine* a, const tachyon_bn254_g2_affine* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_projective_eq(
    const tachyon_bn254_g2_projective* a, const tachyon_bn254_g2_projective* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_jacobian_eq(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_jacobian* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_xyzz_eq(const tachyon_bn254_g2_xyzz* a,
                                               const tachyon_bn254_g2_xyzz* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_affine_ne(
    const tachyon_bn254_g2_affine* a, const tachyon_bn254_g2_affine* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_projective_ne(
    const tachyon_bn254_g2_projective* a, const tachyon_bn254_g2_projective* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_jacobian_ne(
    const tachyon_bn254_g2_jacobian* a, const tachyon_bn254_g2_jacobian* b);

bool TACHYON_C_EXPORT tachyon_bn254_g2_xyzz_ne(const tachyon_bn254_g2_xyzz* a,
                                               const tachyon_bn254_g2_xyzz* b);

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // TACHYON_C_MATH_ELLIPTIC_CURVES_BN_BN254_G2_H_
